ALTER TYPE "ScoreEventType" ADD VALUE IF NOT EXISTS 'FORTRESS_UPGRADE_PURCHASE';
ALTER TYPE "ScoreEventType" ADD VALUE IF NOT EXISTS 'FORTRESS_UPGRADE_SLAYER_BONUS';

ALTER TABLE "Cycle"
ADD COLUMN "upgradesUnlockedAt" TIMESTAMP(3);

ALTER TABLE "Fortress"
ADD COLUMN "level" INTEGER NOT NULL DEFAULT 0;
