CREATE TYPE "FortressDoctrine" AS ENUM (
  'DWARF_HOLDFAST',
  'DWARF_WATCHKEEPERS',
  'ORK_MARAUDERS',
  'ORK_SIEGEBREAKERS',
  'MURINE_CONVOY_COMMAND',
  'MURINE_RAPID_RESPONSE',
  'UNICORN_GLITTER_FRONTIER',
  'UNICORN_VEILED_NETWORK'
);

ALTER TABLE "Fortress"
ADD COLUMN "doctrine" "FortressDoctrine",
ADD COLUMN "doctrineChangedAt" TIMESTAMP(3);
