ALTER TABLE "WarPolicy"
  ADD COLUMN IF NOT EXISTS "allianceSupportAttack" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allianceSupportDefense" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allianceSupportPercent" INTEGER NOT NULL DEFAULT 50;
